### ISSUE TITLE
[4h] Auto-mentions in replies not working correctly

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#106]
## Auto-mentions in replies are mentioning incorrect people.
![bug1](https://user-images.githubusercontent.com/11751592/53579748-33f99b80-3b8b-11e9-9768-10f8ef29ed35.jpg)
When you start replying to a comment, and there is a comment on a lower level, you mention the author of this lower-level comment, not the comment you've clicked `reply` on.
### Steps to reproduce:
Click `reply` to a comment that has other replies. Enjoy auto-mention pointing to the author of this reply, not the comment you are replying to.
### Expected behavior:
Auto-mention should mention the author of the comment you've clicked `reply` to.

**Comment by dimalitvinov** [comment]
#106 resolve
