### ISSUE TITLE
[16h] Add trust feature

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#144]
Trust feature should be associated with account profile info and represent its trustability inside the network.

Design:
https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=2992%3A1271

**Comment by shdwdmn** [comment]
Trust notifications text is empty:
![Screenshot from 2019-04-01 15-58-54](https://user-images.githubusercontent.com/46528935/55330679-4fadd580-549a-11e9-9762-59b750311880.png)

**Comment by sudokey** [comment]
> Trust notifications text is empty:
> ![Screenshot from 2019-04-01 15-58-54](https://user-images.githubusercontent.com/46528935/55330679-4fadd580-549a-11e9-9762-59b750311880.png)

fixed
