### ISSUE TITLE
 [10h] Add mentions to about and status message in profiles + #149

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#150]
Add mentions to `about` and `status` message in profiles.
Mentions should work like in comments - search popup and automatic link.

+ #149

**Comment by shdwdmn** [comment]
Redundant leading space in a post (also in a comment, about, status) if started with tag or mention
![2result](https://user-images.githubusercontent.com/46528935/55539103-8d904100-56c8-11e9-8946-c4b3d6400e4c.png)
