### ISSUE TITLE
[1h] Follow/Join button text in sub-header does not change to Following/Joined

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.frontend#180]
Follow/Join button text in sub-header does not change to Following/Joined right after the button was pressed. Though it changes after reloading the page.
![112](https://user-images.githubusercontent.com/46528935/56132158-f366ad80-5f91-11e9-8017-8579d762c4dc.png)

### Steps to reproduce:
- for Follow/Following buttons:
1. Open any Community page (e.g., https://staging.u.community/communities/107). 
2. Hover on Sub-header with community author's username, find the Follow (or Following) button
3. Click on the Follow button

- for Join/Joined buttons:
1. Open community's post page  (e.g., https://staging.u.community/posts/14317). 
2. Hover on Sub-header with community's name, find the Join (or Joined) button
3. Click on the Join button

### Expected result:
Button text changed from 'Follow' to 'Following' (or 'Join' to 'Joined'), the checkmark is displayed (or vice versa).

### Actual result:
Checkmark is displayed, but the button text doesn't change. Though it changes after reloading the page.

**Comment by vladimirice** [comment]
cannot reproduce
