### ISSUE TITLE
Can't login after registration

### ISSUE THREAD

**Issue by sxiii** [UOSnetwork/ucom.frontend#19]
Hi! I've recently registered as `securityxiii`.

I have my brainkey. Now, while I'm trying to login with this name and my brainkey, system says that there is no such account in the blockchain. But when I'm trying to create account with this name, system says, that the name is already occupied. 

What to do in this case? :)

**Comment by Sxela** [comment]
Have you been copy-pasting it? If so, plese try typing it in, exactly 12 lowercase words separated by 1 space, without any additional spaces at the start or end of the line.

**Comment by Sxela** [comment]
@sxiii How's it going? Is the issue still relevant?

**Comment by Sxela** [comment]
@sxiii I'm closing this issue as incative, feel free to open it again if the problem still persists!

Please check account name (it has really helped some people). After that you'd need to enter all 12 words, lowercase, separated by 1 whitespace. There should be no extra spaces at the beginning or end of the phrase.
