### ISSUE TITLE
Transfers page does not show peer 2 peer transfers

### ISSUE THREAD

**Issue by iamredbar** [UOSnetwork/ucom.frontend#207]
Transfers page does not show p2p transactions
-----

Summary
-------

The only transfers that show up on the transfers page are from emission collection, staking, and BP voting. Peer 2 Peer transactions do not appear.

Environment
-----------

Brave Browser Version 0.62.51

Steps to reproduce
------------------

- Observe wallet from U°Community
- P2P transactions are not there
- Observe explorer.u.community, user iamredbar1bp, and see p2p transfers

Expected result
---------------

Show all types of transfers on the transfers page

Current result
--------------

No p2p transfers, only other types of transfers

(picture is showing where a p2p transfer should be, but is not)
![Screen Shot 2019-04-21 at 8 48 23 AM](https://user-images.githubusercontent.com/16945982/56471142-95fcb180-6414-11e9-8fc6-bdd6f88fb53b.png)

![Screen Shot 2019-04-21 at 8 58 14 AM](https://user-images.githubusercontent.com/16945982/56471146-a876eb00-6414-11e9-830a-8b14d70c1e34.png)

**Comment by Sxela** [comment]
u.community wallet activity should be fine by now. As for the explorer.uos.network, the problem still persists.
