### ISSUE TITLE
Fix "Successfully buy/sell ram" messages

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.frontend#225]
Both "Successfully buy/sell ram" messages should be fixed as grammatically incorrect.

Expected messages: to be clarified (proposal: "Successfully bought/sold RAM")

![image](https://user-images.githubusercontent.com/46528935/56581344-6b118980-65dd-11e9-8cf2-e60556eeb9b9.png)

**Comment by sudokey** [comment]
Fix in https://github.com/UOSnetwork/ucom.frontend/issues/165
