### ISSUE TITLE
[4h] Fix case sensitive search in mentions

### ISSUE THREAD

**Issue by sudokey** [UOSnetwork/ucom.frontend#252]
- [ ] fix ```@Ivanov``` and ```@ivanov``` returned different results (both are invalid according to backend response, see attached pic) (inline text search only, top bar search is okay)
- [ ] fix search pop-up overlap entered text (inline text search only)
- [ ] fix redundant search on cursor movement (left and right) (inline text search only)
- [ ] fix duplicated search requests (top bar search only)
- [ ] don't send OPTIONS request every time (cache response)
- [ ] don't send request with less than 2 letters to search
- [ ] set min delay between requests (~500 ms)
![image](https://user-images.githubusercontent.com/46528935/57302957-fcf0ba80-70e4-11e9-9610-76f780460071.png)

**Comment by Sxela** [comment]
Let's also accept both `@username` and `username` inputs.
