### ISSUE TITLE
Fix user rate displayed as a fraction

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.frontend#262]
User rate displayed as a fraction (0.0123456789) in case previous page is Edit Profile page.

### Steps to reproduce
1. Open Edit Profile page
2. Make any changes, press Submit 
3. Check user rate at the page header

### Expected result
User rate is displayed as an integer.

### Actual result
User rate is displayed as a fraction.

![image](https://user-images.githubusercontent.com/46528935/57687729-a2a3ac80-7644-11e9-9303-fef9ca08a838.png)

**Comment by sudokey** [comment]
```/api/v1/myself``` response contains wrong data
