### ISSUE TITLE
[14h] Add GitHub Airdrop round 2

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#275]
Add 2nd round of github airdrop with the following conditions:
* multiply token amount by 100
* credit zero-score users with 100 UOS
* display score immediately after github authorization 
* token pools = 1 000 000 UOS, 1 000 000 UOSF
* add sharing condition and menu to the checklist (doesn't affect user status, flag is stored in local storage)
* redirect https://u.community/github to offer post when Round 2 starts

Optional:
* add tiers to score

### Testing rounds
1. Staging offer https://staging.u.community/posts/14786
2. Production offer https://u.community/posts/8515
	- to clean up test users from participants (?)

### CHECKLIST
Check the following after user registered in Airdrop:
* last receipts returned by API ('Get airdrop state' request): find account name as "accname", verify:
	- "external_id" matches with GH ID
	- "amount" and "symbol" matches received tokens values
* airdrop pool decreased by exact received tokens values (test holder - testairdrop1, prod holder - airdrop11111)
* for users migrated from GitHub Airdrop round 1: check airdrops_users_external_data DB table

Users pool:

| gh_user_name | gh_user_id | score_stg | amount_stg | R1_stg | R2_stg | score_prd | amount_prd | R1_prd | R2_prd |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| shdwdmn | 46528935 | 5.555555 | 59513 | multi | | 5.555555 | 59513 | denismelnich | |
| denismelnichuk | 49903415 | 4.444444 | 49720 | ? | | 1.000001 | 10712 | - | - |
| denismelnitest | 50102691 | 33.33333 | 33333 | multi | | 0 | 0 | - | |
| denismelnitesti4 | 50102974 | 2.222222 | 123456 | testuser1155 | + | 0 | 0 | testuser1141 | |
| denismelnitesti44 | 50136878 | 1.111111 | 12345 | - | testuser1211 | 0 | 0 | testuser1144 | |
| denistesti4 | 50327754 | 0 | 0 | testuser1145 | + | 0 | 0 | testuser1152 | |
| denistesti44 | 50327835 | 0 | 0 | - | testuser1213 | 0 | 0 | testuser1153 | |
| denistesti444 | 50867288 | 164.2197 | 1759183 | - | - | 164.2197 | 1759183 | - | - |
| ghr2test1111 | 50946830 | 0 | 0 | - | + | 0 | 0 | - | - |
| ghr2test1112 | 50947277 | 0 | 0 | - | + | 0 | 0 | - | - |
| ghr2test1113 | 50947447 | 0 | 0 | - | + | 0 | 0 | - | - |
| ghr2test1114 | - | 0 | 0 | - | - | 0 | 0 | - | - |
| ghr2test1115 | 50948719 | 191.1349  | 2041349 | - | testuser1214 | 191.1349  | 2041349 | - |  - |
| ghr2test1116 | - | 341.0093 | 3911034 | - | - | 341.0093 | 3911034 | - | - |
| ghr2test1117 | - | 109.9341 | 1221943 | - | - | 109.9341 | 1221943 | - | - |
| gemmedtuterrn | 50949553 | 0 | 0 | - | testuser1215 | 0 | 0 | - | testuser1213 |
| galidatuterrn | 50949679 | 0 | 0 | - | testuser1221 | 109.9341 | 1221943 | - | testuser1214 |

**Comment by akegaviar** [comment]
Pub link for the offer https://u.community/posts/8050

Also pls set it to https://u.community/github when Round 2 starts.
