### ISSUE TITLE
[32h] New main page

### ISSUE THREAD

**Issue by sudokey** [UOSnetwork/ucom.frontend#310]

**Comment by Yopur** [comment]
Publication Preview:
- You need to enlarge background pictures on hover
- Also on hover darkening layer must be set to 36% opacity
- Title on hover must not become transparent

**Comment by Sxela** [comment]
https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=5180%3A61
- design

**Comment by Sxela** [comment]
Tabs: 
# Communities 
## Featured
Featured publicatons section
Top publications  made in communities by community members.
Ranged by Importance.
## Feed
Direct posts made in communities

## Call to Action Sidebar
Link to an internal u.community page
## Top Communities This Week Sidebar
“Top communities this week” section 
Works like trending, but the timeframe is one week - 
* Pick a weekly delta in communities' importance.
* Display top communities  sorted by importance weekly delta 
## Recent Top Authors Sidebar
“Recent top Authors” section 
Works like trending, but the timeframe is one day - 
* Pick a delta in people's importance for one day (24h).
* Filter people having at least 1 post or publication made during this day (24h)
* Display people sorted by importance delta  
## Popular Today Sidebar
“Popular Today” section 
Works like trending, but the timeframe is one day - 
* Pick a delta in tags' importance for one day (24h).
* Filter tags used at least in 1 post or publication during this day (24h)
* Display tags sorted by importance delta

**Comment by Sxela** [comment]
<img width="439" alt="Screenshot 2019-06-05 at 11 17 47" src="https://user-images.githubusercontent.com/11751592/58941010-96ae9480-8783-11e9-8cd0-ce49c15c8fbf.png">

**Comment by Sxela** [comment]
<img width="432" alt="Screenshot 2019-06-05 at 11 18 33" src="https://user-images.githubusercontent.com/11751592/58941057-acbc5500-8783-11e9-82c9-557830b5a0d2.png">
