### ISSUE TITLE
General Info Page Under About Page Gives 404

### ISSUE THREAD

**Issue by Kennybll** [UOSnetwork/ucom.frontend#41]
Title
-----

General Info Page Under About Gives 404

Summary
-------

When I go to [/about](https://u.community/about) it redirects to [/about/general-info](https://u.community/about/general-info) but the src/routes.js file doesn't have support for that route giving off a 404.

Environment
-----------

Windows 10, Chrome (Latest)

Steps to reproduce
------------------

Go to [https://u.community/about](https://u.community/about).

Expected result
---------------

![image](https://user-images.githubusercontent.com/14302151/51804617-5c5f4480-2231-11e9-8911-e97edfd98ef8.png)

Current result
--------------

![image](https://user-images.githubusercontent.com/14302151/51804616-4d789200-2231-11e9-9bdd-a99f495f07f6.png)

Possible Fix
------------

Update src/routes.js to serve the About.jsx page when redirecting to /about/general-info.

Additional information
----------------------

I got a fix, going to add a PR.

Examples
--------

https://github.com/UOSnetwork/ucom.frontend/blob/master/src/routes.js#L57

**Comment by Sxela** [comment]
Thanks for the input, we will look into it as soon as possible!
