### ISSUE TITLE
X button not closing the screen on the wallet

### ISSUE THREAD

**Issue by iamjustjag** [UOSnetwork/ucom.frontend#463]
type of user = signed in user

Environment  
Platform = Lenovo Win7 PC
OS = windows 7 home basic x64 Service Pack 1
Browser = firefox quantum 69.0.1 x64 rus

Page = Header > Wallet Icon > Header > X button

action = no pointer on the X button to close the wallet screen
![Screenshot_1](https://user-images.githubusercontent.com/56133337/66159643-157fe500-e631-11e9-918c-81aea5b7fc29.png)

closest URL = https://u.community/user/xxxx

Steps:

1/ as a non-logged in visitor, access homepage: https://u.community
2/ sign in as USER : @account_name / private social key
3/ go to header
4/ click on "wallet icon" on the right side of the page
5/ observe you've entered to the personal account wallet
6/ go to header
7/ click on the "X" button on the right side of the page

**Comment by sudokey** [comment]
Thank you for report. Fixed.

**Comment by iamjustjag** [comment]
Appreciate it!
