### ISSUE TITLE
[4h] web-site is not displaying on Community

### ISSUE THREAD

**Issue by akegaviar** [UOSnetwork/ucom.frontend#59]
## Current Behavior
On Community profile, providing a website in the `web-site` field does not publish the website

## Environment
Client independent

## Steps to reproduce
1. Create a Community or edit an existing Community
2. Add a website in the `web-site` field
3. Click `Finish`
4. The website link is not on the Community profile

## Expected behavior
The website link and field are published.

**Comment by Sxela** [comment]
Design: https://www.figma.com/file/R3hb0URSjivbarZr5bbnWaiS/U_in-progress?node-id=2592%3A46209
(look for a link icon in `Social Networks` sidebar - that's where it should be displayed)
