### ISSUE TITLE
[1h]No 'GitHub' field on Community profile 

### ISSUE THREAD

**Issue by akegaviar** [UOSnetwork/ucom.frontend#61]
## Current Behavior
On Community profile, there's no way to add GitHub on the `Contacts` tab. The only options are Facebook, Reddit, Medium, Twitter

## Environment
Client independent

## Steps to reproduce
1. Create a Community or edit an existing Community
2. Click `Contacts`
3. There's no way to add anything other than Facebook, Reddit, Medium, Twitter

## Expected behavior
Field `GitHub` exists and is published to the Community profile on github link input.

**Comment by Sxela** [comment]
GitHub icon required.

**Comment by Sxela** [comment]
Done. Next time use correct automation syntax, like 'fix #61'
