### ISSUE TITLE
[26] U°Community main menu bar

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#66]
https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=1680%3A1141
- [x] [18h] Desktop markup 
- [x] [8h] Mobile markup

**Comment by Yopur** [comment]
- [ ] Pop-up border
- [ ] Hover behaviour for search icon, burger sign and other menu items like hover on notification bell
- [ ] Easing on shadow for floating menu
- [ ] Avatar hover fix
