### ISSUE TITLE
[24h] Basic search system implementation

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#73]
https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=1680%3A1141

1. Use already existing search for people.
1. Display results and suggest seraching for more via DuckDuckGo (site:u.community + `search_query`)

3. input on mobile
4. do not work on page Users

**Comment by dimalitvinov** [comment]
#73 resolve
